# Generated by Django 4.1 on 2024-10-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_lpa7user_options_lpa7user_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpa7user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='avatar'),
        ),
    ]
